export const PROFILE_CACHE_TTL_MS = 15 * 60 * 1000;
export const MANUAL_PROFILE_REFRESH_COOLDOWN_MS = 20 * 1000;
export const BEST_UMA_SCORE_VERSION = 10;
export const BEST_UMA_MIN_MATCHES = 3;
export const RECENT_HISTORY_VERSION = 1;
export const RECENT_HISTORY_ANALYSIS_MATCHES = 20;
export const RECENT_HISTORY_DISPLAY_MATCHES = 5;
